
name: Self Hosted Runner

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run the script
        run: |
          podman run --rm -v ${GITHUB_WORKSPACE}\stop.sh:/script.sh testshellcheck /script.sh > ${GITHUB_WORKSPACE}\output.txt

          more ${GITHUB_WORKSPACE}\output.txt
