
name: Self Hosted Runner

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Show workdir
        run:
          echo "${{ github.workspace }}"

      - name: Run Linting
        run: |
          echo ${{ github.workspace }}/stop_copy.sh
          podman run --rm --privileged -v ${{ github.workspace }}/stop_copy.sh:/script.sh testshellcheck /script.sh > ${{ github.workspace }}/output.txt

                    # Use script to determine if a PR should be created (exit 0 to create PR, exit 1 to skip PR creation)
          expected_text="Linting /script.sh"
          
          # Use `cat` to read the contents of the file
          file_contents=$(cat "${{ github.workspace }}/output.txt")                   
          
