
name: Self Hosted Runner

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Show workdir
        run:
          echo "${{ github.workspace }}"

      - name: Run the script
        run: |
          podman run --rm --privileged -v ${{ github.workspace }}/stop.sh:/script.sh testshellcheck > ${{ github.workspace }}/output.txt

          more ${{ github.workspace }}/output.txt
          
          
